Feature/cdf/american donut
cytosmart-bv/tomni pull request #47
Opened 2023-07-19 13:26 UTC by lisakoolen

Thank you for your contribution to the **Tomni** package.
Before submitting/accepting this Pull Request, please make sure:

## Contributor of code

- [ ] Version number is updated
- [ ] `HISTORY.rst` is updated
- [ ] Function is tested
- [ ] `(docstring)` is added or updated
- [ ] All needed package are in [requirements.txt](requirements.txt)

**For new function**

- [ ] Functions are named based on [Python naming conventions](https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html)
- [ ] Function is added to apidocx.rst
- [ ] New feature is added to `README.md` subsection `Features`
- [ ] New function is imported in all `__init__.py` that are needed

**For bugfix**
- [ ] Unit test is added that covers the bug (if possible)
- [ ] You cursed at the person that introduced the bug

## Reviewer

- [ ] Version number is updated
- [ ] `HISTORY.rst` is updated
- [ ] Function is tested
- [ ] `(docstring)` is added or updated
- [ ] All needed package are in [requirements.txt](requirements.txt)

**For new function**

- [ ] Functions are named based on [Python naming conventions](https://visualgit.readthedocs.io/en/latest/pages/naming_convention.html)
- [ ] Function is added to apidocx.rst
- [ ] New feature is added to `README.md` subsection `Features`
- [ ] New function is imported in all `__init__.py` that are needed

**For bugfix**
- [ ] Unit test is added that covers the bug (if possible)

2023-07-24 11:24 UTC, Bram-van-der-Velden commented on tomni/annotation_manager/utils/main.py
> +) -> np.ndarray:
```suggestion
) -> List:
```

2023-07-24 11:28 UTC, Bram-van-der-Velden commented on tomni/annotation_manager/annotations/polygon/main.py
> +        self._inner_contour: np.ndarray = parse_points_to_inner_contour(inner_points)
inner contourS

2023-07-24 11:35 UTC, Bram-van-der-Velden commented on tomni/annotation_manager/annotations/polygon/main.py
> +        self._area = self._outer_area
just do self._area in 1 go and substract the inner areas instead of renaming a variable

2023-07-24 11:35 UTC, Bram-van-der-Velden commented on tomni/annotation_manager/annotations/polygon/main.py
> +        self._area = self._outer_area
or have a temp area and then at the end self._area = temp_variable

2023-07-24 11:39 UTC, Bram-van-der-Velden commented on tomni/annotation_manager/annotations/polygon/main.py
> +        self._area_outer: Union[float, None] = None
says area_outer here but everywhere else its _outer_area

2023-07-24 11:41 UTC, Bram-van-der-Velden requested changes
comments

2023-08-01 08:36 UTC, jellevankerk commented on tomni/annotation_manager/test_annotation_manager.py
> +    def test_labeled_mask_classes_mismatch_2(self):
this should not fail. if model expects to predict 2 labels but on 1 image it only sees one label it should not fial

2023-08-01 13:00 UTC, jellevankerk approved these changes

2023-08-01 13:05 UTC, merged